<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>RemoteWake.Launcher.Wpf</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../RemoteWake.Application/RemoteWake.Application.csproj" />
    <ProjectReference Include="../RemoteWake.Domain/RemoteWake.Domain.csproj" />
  </ItemGroup>
</Project>
